import shutil
import os
import random
from PIL import Image
cont = random.random()
erro=0
for file in  os.listdir('.'):
    print("Image name:",file)
    # resize an image using the PIL image library
    # free from:  http://www.pythonware.com/products/pil/index.htm
    # tested with Python24        vegaseat     11oct2005
    # open an image file (.bmp,.jpg,.png,.gif) you have in the working folder
    try:
        im1 = Image.open(open(file, 'rw'))
        # adjust width and height to your needs
        width = 24
        height = 24
        # use one of these filter options to resize the image
        im5 = im1.resize((width, height), Image.ANTIALIAS)    # best down-sizing filter
        name=str(cont)+".png"
        im5.save(name)
        shutil.move(name, "Resized/")
        os.remove(file)
        # optional image viewer ...
        # image viewer  i_view32.exe   free download from:  http://www.irfanview.com/
        # avoids the many huge bitmap files generated by PIL's show()
        print("Image name: to ",file,cont)
        cont=cont+1
    except IOError:
        erro
        erro+=1
